export type EvidenceLink = { title: string; description: string; href: string; entity?: string; image?: string; alt?: string };
const origin = "https://livingdentalhealth.com";
const doctor: EvidenceLink = { title: "Meet Dr. Andy Engel", description: "Practicing in Bend since 1998. OHSU DMD, with more than 1,000 hours of continuing education in smile design, cosmetic dentistry, and full mouth reconstruction.", href: "/about", entity: `${origin}/#doctor` };
const veneers: EvidenceLink = { title: "Porcelain veneers: a fuller smile", description: "See the existing before-and-after case and how photography, a diagnostic wax-up, and smile design guided treatment for chipped and discolored teeth.", href: "/before-and-after#case-01", entity: `${origin}/before-and-after#case-01`, image: "/case-01.webp", alt: "Before and after porcelain veneers by Dr. Andy Engel — Case 01" };
const reconstruction: EvidenceLink = { title: "Rebuilding worn and damaged teeth", description: "See the existing full mouth reconstruction case combining crowns and veneers to address worn teeth and restore function and appearance.", href: "/before-and-after#case-02", entity: `${origin}/before-and-after#case-02`, image: "/case-02.webp", alt: "Before and after full mouth reconstruction by Dr. Andy Engel — Case 02" };
const crowns: EvidenceLink = { title: "Restoring worn teeth with crowns", description: "See how a diagnostic wax-up and smile design informed porcelain crowns for broken, chipped, and shortened teeth.", href: "/before-and-after#case-03", entity: `${origin}/before-and-after#case-03`, image: "/case-03.webp", alt: "Before and after porcelain crowns by Dr. Andy Engel — Case 03" };
const cosmetic: EvidenceLink = { title: "Cosmetic dentistry and smile design", description: "Explore veneers, bonding, whitening, and clear aligners, with a plan based on your teeth, bite, and goals.", href: "/cosmetic-dentistry", entity: `${origin}/cosmetic-dentistry#webpage` };
const full: EvidenceLink = { title: "Full mouth reconstruction", description: "Learn how Dr. Engel plans coordinated care for extensively worn, damaged, or missing teeth.", href: "/full-mouth-reconstruction" };
const implants: EvidenceLink = { title: "Dental implant care", description: "Explore assessment, imaging, placement, and restoration planning with Dr. Engel.", href: "/dental-implants" };
const story: EvidenceLink = { title: "A smile story from Dr. Engel", description: "An existing article describes replacing discolored older composites with eight crowns and veneers, and explains his individualized approach.", href: "/articles/starting-the-new-year-with-a-confident-smile" };
const reviews: EvidenceLink = { title: "Read patient reviews", description: "Explore patient feedback on Living Dental Health’s PatientConnect365 profile.", href: "https://www.patientconnect365.com/Dentists/Oregon/Bend/97702/Living_Dental_Health" };
export const careEvidence = {
  home: { title: "Get to know the dentist. See the work.", intro: "Choosing a dentist is personal. Explore Dr. Engel’s background, the care he provides, and examples of treatment completed here in Bend.", links: [doctor, veneers, reconstruction, reviews] },
  about: { title: "See how his training connects to your care", intro: "Explore the treatments Dr. Engel provides and the cases that show his approach to planning and restoring smiles.", links: [cosmetic, full, implants, veneers, reconstruction, crowns, reviews] },
  cosmetic: { title: "See Dr. Engel’s cosmetic work", intro: "Start with his background, then explore actual cases and the planning behind them. Each patient’s treatment and outcome is individual.", links: [doctor, veneers, crowns, story, reviews] },
  reconstruction: { title: "Experience behind your reconstruction", intro: "Read about Dr. Engel’s training and see examples of the restorative work described on this page. Individual treatment needs and outcomes vary.", links: [doctor, reconstruction, crowns, cosmetic, reviews] },
  implants: { title: "Make an informed choice about implant care", intro: "Learn about Dr. Engel’s background and compare replacement options before discussing your own treatment plan.", links: [doctor, { title: "Implant or bridge?", description: "Compare how each option is supported, what planning involves, and which questions to bring to your appointment.", href: "/articles/dental-implants-vs-dental-bridges-filling-the-gap-in-your-smile" }, { title: "Bone grafting and implant planning", description: "Understand when additional bone support may be considered and how it fits into an individual plan.", href: "/bone-grafting" }] },
  general: { title: "Meet your dentist and explore his restorative work", intro: "From preventive visits to restoring damaged teeth, learn who will provide your care and see examples of his work.", links: [doctor, crowns, { title: "Your first dental appointment", description: "Find out what to bring, what the examination includes, and how your next steps are planned.", href: "/articles/understanding-your-first-dental-appointment-at-living-dental-health" }] }
} satisfies Record<string, {title: string; intro: string; links: EvidenceLink[]}>;
export type EvidenceKey = keyof typeof careEvidence;
export const practiceAwards = [
  { label: "2026 Platinum — Dental Hygiene Clinic", href: "https://bend.communityvotes.com/2026/01/healthcare/dental-hygiene-clinic" },
  { label: "2025 Platinum — Dental Hygiene Clinic", href: "https://bend.communityvotes.com/2025/01/healthcare/dental-hygiene-clinic" },
  { label: "2025 Gold — Dental Clinic", href: "https://bend.communityvotes.com/2025/01/healthcare/dental-clinic" }
];
